### ISSUE TITLE
Possible refactor options

### ISSUE THREAD

**Issue by Janmm14** [JamieSinn/TrailGUI#1]
- Create enum `Trail` for OOP
- Use EnumMultimap<UUID, Trail> to save player-related data (needs some conversion for cfg but that's nothing hard)
- Move some static things to `Trail` enum

**Comment by JamieSinn** [comment]
I'll do this as the next major update, you're welcome to submit PR's whenever.

**Comment by Janmm14** [comment]
I'm starting coding these things now.

**Comment by Janmm14** [comment]
Progress, once pushed, here: https://github.com/Janmm14/TrailGUI/commits/oop

**Comment by JamieSinn** [comment]
Merged into #2
