### ISSUE TITLE
Particle Modifiers

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#10]
If you are taking suggestions for potential future features, I possibly got one. Thoughts on particle modifiers? Such as changing position from feet to head, or animations like halo, vortex, sphere, ring, twister, spiral, etc? Some examples can be found here. https://www.spigotmc.org/resources/customparticleeffects.2725/

I'm not sure how resource intensive it would be or if it is even a good suggestion. I'm perfectly happy with the current minimalistic approach (and prefer it) with trails only occurring when moving, but just thought I should throw the idea out there in case it interests you or anyone else. :)

**Comment by Janmm14** [comment]
The position relative to the feet is already changeable by the *-displayLocation option.

Also I wanted to implement a config option whether it draws every x ticks or on movement

**Comment by JamieSinn** [comment]
As said above, this is a config option. And I'll be changing it to only draw on move due to lag.
