### ISSUE TITLE
Add the ability to change what block/item is used with IconCrack/BlockBreak

### ISSUE THREAD

**Issue by JamieSinn** [JamieSinn/TrailGUI#14]

**Comment by goosewoman** [comment]
pretty sure this is already done

**Comment by JamieSinn** [comment]
I meant by command, eg.
/trail blockbreak <block>
/trail blockbreak GRASS

**Comment by goosewoman** [comment]
But you can already add an unlimited amount of trails through the config.

**Comment by JamieSinn** [comment]
Eh, true. 
I'll close this now.
