### ISSUE TITLE
Possible improvements and refactor

### ISSUE THREAD

**Issue by Janmm14** [JamieSinn/TrailGUI#2]
- Different options when trails get painted
  - On player move
  - Every x tick
  - Both maybe?
- Show in item's lore in GUI whether its currently enabled or not
- Options about unavailable trails
  - Do not show
  - Show as unavailable
- Create enum `Trail` for OOP
- Use EnumMultimap<UUID, Trail> to save player-related data (needs some conversion for cfg but that's nothing hard)
- Move some static things to `Trail` enum

**Comment by JamieSinn** [comment]
For the 3rd, check out the dev branch. This is where the WIP things will go before I merge them

**Comment by Janmm14** [comment]
just ignopre that mentiones, they are an issue of my commit message

**Comment by JamieSinn** [comment]
No problem

**Comment by Janmm14** [comment]
@JamieSinn Hey, it would be very nice if you could do some things on my rewrite, as I think you want that also as fast as possible. The next 2 weeks I am too bus to work on that. You can pr it into my fork, I am still able to do a quick look on your code and push.

**Comment by Janmm14** [comment]
Just as an information, I turned away from an enum-based things for extensibility and it was also simpler in my opinion. Player data is now saved in HashMaps directly by UUID -> Trail

**Comment by Janmm14** [comment]
Also I changed unavailable trails in the gui to just show a line in the lore.

**Comment by JamieSinn** [comment]
I'll look into it. I may not have time either, as I am a full time developer for EcoCityCraft.

**Comment by JamieSinn** [comment]
@Janmm14 I've looked at the refactor. 
I don't want to use this until very likely version 5.0.

I'm going to leave this open, but it will not be a priority whatsoever for a while. The current code base is fine as is.

**Comment by JamieSinn** [comment]
Refactored due to @kukelekuuk00's amazing refactor.

Thanks!

Closed.

**Comment by Janmm14** [comment]
Well in my opinion its a bad refactor, but I don't wanna argue.

And:

> The current code base is fine as is.

You don't mean that serious hopefully!?

**Comment by JamieSinn** [comment]
The refactor kuke made is good. Feel free to change it as you wish and I'll review

**Comment by goosewoman** [comment]
Could you explain what exactly about my refactor you believe is bad?

**Comment by Janmm14** [comment]
"current code base" was referred to the one before your refactor

**Comment by JamieSinn** [comment]
"Well in my opinion its a bad refactor, but I don't wanna argue."
