### ISSUE TITLE
Item attributes present.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#22]
TrailGUI dev 34

Any possible way to disable item attributes being displayed in the trail GUI?

![l](http://i.imgur.com/sicVC8f.png)
![l2](http://i.imgur.com/GUGSz7T.png)

I know that the Chest Commands GUI plugin does not display item attributes in their inventory menus.
http://dev.bukkit.org/bukkit-plugins/chest-commands/
https://github.com/filoghost/ChestCommands

**Comment by JamieSinn** [comment]
I'll look into this.

**Comment by JamieSinn** [comment]
Possibly will be fixed. Not actually too worried as the item can be changed.
