### ISSUE TITLE
BlackDust trail broken.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#24]
TrailGUI dev 34

The BlackDust trail does not create only a black dust line. Instead, it is black redstone dust mixed with colored dust. Similar to the color red dust trail, except darker colors.

**Comment by JamieSinn** [comment]
This is mostly just a config option. I'll keep it as is for now, and look into it more later.

**Comment by mibby** [comment]
Perhaps it may just be a config option, but shouldn't it actually be fixed to only display a black redstone dust particle instead of being a rehashed version of the ColoredRedDust trail?

**Comment by goosewoman** [comment]
fixed in https://github.com/JamieSinn/TrailGUI/commit/021e283bcdfd2c14473f242f84079faafd06e693
You can already edit your config by replacing the 0.01 with 0

**Comment by mibby** [comment]
@kukelekuuk00 That commit did not fix the issue. The 'BlackDust' trail is now just a red redstone dust particle instead of mixed colors. It is not black.

It would be nice to confirm yourself before stating it is fixed, or wait until it is confirmed fixed before closing the ticket...

**Comment by goosewoman** [comment]
Okay. Looks like I did make a mistake.
I'm not available for immediate testing, so I'll ask you to do it for me. Could you set the speed value to 0.00000001? It should fix it.

**Comment by mibby** [comment]
Confirmed `0.00000001` speed fixes the issue. Feel free to commit the change to the repo.

**Comment by goosewoman** [comment]
fixed in https://github.com/JamieSinn/TrailGUI/commit/a8776bd6b627691a8800c2a8cf72163ef185247c
