### ISSUE TITLE
Click to toggle text trails.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#26]
Suggestion. When typing `/trail`, display all trails the user has access to. Users would be able to toggle a trail state by clicking on the text of the trail name. The text color would indicate whether or not the trail is enabled or not - red being disabled, green being enabled. Obviously limited to the max number of active trails setting.

'values:' would have to be removed from the text output to make it pretty.

**Comment by JamieSinn** [comment]
Will be done in next release.

**Comment by JamieSinn** [comment]
Just looked into this. 

I'll sort it by alphabetical, but not clicking.
