### ISSUE TITLE
TrailGUI v4.2.1 doesn't care about the item displaynames in the config

### ISSUE THREAD

**Issue by hankur** [JamieSinn/TrailGUI#32]
Every item in the trails menu has an italic white name, which is the name of the trail, not the displayname of that item set in config.

This is the menu after letting the plugin generate it's default config:
http://gyazo.com/bf412be766212ca53a391d82dacec74b

Tested with the latest TrailGUI build from spigotmc.org, ci.md-5.com and ci.ecocitycraft.com.

**Comment by hankur** [comment]
It still isn't fixed, unfortunately. Tested with the build 13 from ci.ecocitycraft.com.

**Comment by JamieSinn** [comment]
I tested this last night and it worked fine, please post reproduction steps

**Comment by hankur** [comment]
Tested it right now on my Bungeecord server:
1. Compiled the latest Spigot 1.8.8 build with the latest BuildTools (#42 from Jenkins).
2. Started the server, stopped the server.
3. Set EULA=true.
4. Started the server, let it generate files, stopped the server.
5. Edited server port and set onlinemode=false.
6. Downloaded latest TrailGUI version from spigotmc.org (v4.2.2), copied it to /plugins folder.
7. Started the server, logged in, opped myself.
8. Ran command /trails and hovered over the items.
9. Voila: https://gyazo.com/a9bcb45d20e3e5576af34e5ac45eedc9
   The naviagtion buttons and "Remove Trails" button are colored though: https://gyazo.com/1cc38912dfa63ea1e2da39327de2541b
