### ISSUE TITLE
BlockBreak permission not giving access to the BlockBreak trail.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#34]
Giving user both the `trailgui.inventory.blockbreak`and the `trailgui.trails.blockbreak`, they can't access the BlockBreak trail via command or GUI.

**Comment by mibby** [comment]
Could it be due to the trail being named BlockCrack in the config by default?

**Comment by JamieSinn** [comment]
Yes, that is what it is from. 
I'll change the default config name.
