### ISSUE TITLE
Trails don't appear in GUI or /trail

### ISSUE THREAD

**Issue by agentroop** [JamieSinn/TrailGUI#37]
Players aren't able to use trails. They are inaccessible via the /trail command or the /trails command (the GUI is empty except for "Remove All Trails")
There are no errors on server startup.
My server is running on Spigot 1.8.8.
I'm using the latest Jenkins build, but I also tried the latest build on Spigot.

Config: http://pastebin.com/2jPxaS3H

**Comment by JamieSinn** [comment]
This is the old config. Delete it, start server and see what happens.

**Comment by agentroop** [comment]
Thanks!
