### ISSUE TITLE
1.9 Overhaul

### ISSUE THREAD

**Issue by JamieSinn** [JamieSinn/TrailGUI#38]
To Do:

~~Convert to new API~~
Extend current TrailGUI API

**Comment by JamieSinn** [comment]
Done.

**Comment by mibby** [comment]
Any plans on adding support for 1.9 particles, like a dragon breath trail?

**Comment by JamieSinn** [comment]
Yep, will be doing them once I'm done updating https://github.com/andrewkm/SkylandsPlus

**Comment by JamieSinn** [comment]
Done.

**Comment by mibby** [comment]
Great! Don't forget to add permissions for the new trails.

**Comment by JamieSinn** [comment]
Permissions are not needed to be registered in the pom. 
It's just extra work for me, as people can change the name of the trails and ruin the pom's setup, therefore, not adding any new ones @mibby

**Comment by mibby** [comment]
Ruin the pom? They shouldn't go in the pom. They should be initialized via the plugin.yml to be registered by the server/permissions plugin?

**Comment by JamieSinn** [comment]
My bad, I was tired. I mean the .yml. 
Anyway, they're not 100% needed, only if someone wants to use asterisks on nodes.
