### ISSUE TITLE
Adding colors to inventoryName breaks plugin

### ISSUE THREAD

**Issue by hankur** [JamieSinn/TrailGUI#43]
In config.yml: inventoryName: "Trails" works, but "&cTrails" doesn't.
The plugin still works, but none of the buttons in the GUI work.

**Comment by JamieSinn** [comment]
Colours are not intended to work as inventory titles. Blame bukkit

**Comment by hankur** [comment]
A warning would be great in that case (comment in config file, for example).

**Comment by JamieSinn** [comment]
Will put one in. Thanks.
