### ISSUE TITLE
[Suggestion] Remove trails when player doesn't have permissions for them

### ISSUE THREAD

**Issue by hankur** [JamieSinn/TrailGUI#48]
For example, a player has a timed rank that has permissions for trails. When the rank is taken away, the player will still have those trails activated, because "clearTrailsOnDisconnect" is false. Can you add a permission check on player login and remove the trail when player lacks the permission?

**Comment by JamieSinn** [comment]
This would be quite slow to do. Could you not, on the expiry of the trails (via console) do /trail clearall <{user}>?
