### ISSUE TITLE
Add API for equipping trails for a player

### ISSUE THREAD

**Issue by letsgo00** [JamieSinn/TrailGUI#55]
I would like to have an API where I could equip a trail for a player with or without that player having the permission for that trail (If necessary a permission can be given to players but I'd rather not do that)

**Comment by JamieSinn** [comment]
I'll see about adding this to the 1.13 release

**Comment by JamieSinn** [comment]
https://github.com/JamieSinn/TrailGUI/commit/ca71c501083a3cd4df0b9d0cb5b01f12433bce69
