### ISSUE TITLE
Particles not supported in 1.13.*

### ISSUE THREAD

**Issue by veteranmina** [JamieSinn/TrailGUI#56]
Log of Error: https://pastebin.com/QpVb1NgN

Error: java.lang.IllegalArgumentException: Particle FALLING_DUST requires data, null provided

Above error is occurring with Redstone, ColoredRedDust, Falling Dust and Black Dust.

I have also attempted to use Spigot itself and receive this error, if you need any further information I'll answer back as soon as I can.

Thanks!

**Comment by JamieSinn** [comment]
I don't currently support the 1.13.x versions, if you're able - feel free to submit a pull request.
