### ISSUE TITLE
Cannot remove individual trails

### ISSUE THREAD

**Issue by ghost** [JamieSinn/TrailGUI#65]
When I use /trails and select a trail then close the GUI and reopen it, I am unable to remove any individual trails I had enabled before opening the GUI.

**Comment by JamieSinn** [comment]
Try toggling via the command. Could be a GUI issue.

**Comment by ghost** [comment]
I am able to toggle trails by command but not through the GUI.

**Comment by JamieSinn** [comment]
You likely have a conflicting GUI plugin.

Try to replicate by removing various plugins until it's just TrailGUI. When you find that plugin, report to that author.

**Comment by ghost** [comment]
This happens with only TrailGUI installed on the latest Spigot.

**Comment by JamieSinn** [comment]
If you can provide a replication video/gif, and any stacktraces, that would be a great help. I'm unable to replicate this myself.

**Comment by ghost** [comment]
https://gfycat.com/optimalweepyfruitfly
As you can see in this video, trails that were enabled before typing `/trails` cannot be toggled but all others can.

**Comment by JamieSinn** [comment]
Intereting. I'll look into this.
