### ISSUE TITLE
Won't let me donwload the 1.8 version

### ISSUE THREAD

**Issue by gianni2611** [JamieSinn/TrailGUI#67]
Hello,

I am trying to download the 1.8 version but nothing pops up when I press the link.
I also tried going in the "Version History" section and I tried downloading version 4.3
It then takes me to a page which says "Welcome to Jenkins!" and asks me to login. 

I have no idea what this page is and all I want is to donwload the 1.8 version. Please help me or send me a direct link to the download version please!

Many thanks,
gianni2611

**Comment by JamieSinn** [comment]
https://ci.md-5.net/job/TrailGUI/

The other link has been since taken over by someone else.
