### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#7]
@JamieSinn 

Players by default (non-op / no '*' wildcard permission) can't use trails. Even with both `trailgui.inventory.name` and `trailgui.trails.name` permissions attached to the group. It states 'You do not have permission to use this command'.

Before the permissions overhaul, this permission existed and was required to use trails.  `trailgui.commands.trails` There is no equivalent permission currently present in the plugin.yml or pastebin file.

https://github.com/JamieSinn/TrailGUI/blob/e962881794410f72ef7c0c404fe3388122c4260d/src/main/java/ca/jamiesinn/trailgui/commands/Trails.java#L40

Using version 3.2 with the old permissions, everything functions fine. 

---

```
trailgui.inventory.removetrails
```

Missing from plugin.yml and pastebin file. Also listed twice in the listeners.java file?

https://github.com/JamieSinn/TrailGUI/blob/master/src/main/java/ca/jamiesinn/trailgui/Listeners.java#L1032
https://github.com/JamieSinn/TrailGUI/blob/master/src/main/java/ca/jamiesinn/trailgui/Listeners.java#L1187

---

```
trailgui.inventory.nextpage
```

Listed twice in plugin.yml. No previouspage permission.

https://github.com/JamieSinn/TrailGUI/blob/master/src/main/resources/plugin.yml#L111

**Comment by Janmm14** [comment]
I am currently rewriting this plugin using object orientated programming. You can use the old version or wait until I am finished. Progress can be seen at https://github.com/Janmm14/TrailGUI/tree/oop

**Comment by JamieSinn** [comment]
@Janmm14 I never said that I would be 100% merging all of the PR.
@mibby 
https://github.com/JamieSinn/TrailGUI/blob/master/src/main/java/ca/jamiesinn/trailgui/commands/Trails.java#L40
Still is there.
I'll add it to the relevant files.

It's listed twice for the two inventory pages. A bit redundant, but eh.

I'll fix the permissions errors shortly.

**Comment by mibby** [comment]
Still some inconsistency in permissions in the latest commit. I added comments on the commit itself.

https://github.com/JamieSinn/TrailGUI/commit/6b25dd67b0d699314b77ec9e81fce2100ab9fe87

**Comment by JamieSinn** [comment]
Resolved as of lastest
