### ISSUE TITLE
TrailGUI Version Inconsistency

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#8]
Start-up.

```
[01:00:11] [Server thread/INFO]: [TrailGUI] Loading TrailGUI v3.8
[01:00:16] [Server thread/INFO]: [TrailGUI] Enabling TrailGUI v3.8
```

https://github.com/JamieSinn/TrailGUI/blob/master/src/main/resources/plugin.yml#L3

Shouldn't it be version 3.4 in accordance to the latest resource release on Spigot?

**Comment by JamieSinn** [comment]
Technically, yes. But the numbering system on spigot is not entirely needed. Next update i'll put them in sync

**Comment by Janmm14** [comment]
To 3.4 oder 3.8?
I suggest 3.8, so nobody thinks the clock goes backwards.

**Comment by JamieSinn** [comment]
To 3.8.

**Comment by JamieSinn** [comment]
Resolved.
