### ISSUE TITLE
Hearts & EnderSignal trail not being blocked when having no access to use them.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#9]
Player has no trails. All trails are hidden in the trails menu but the hearts and endersignal trail. When clicking on the trail, it states you do not have permission to do this. Shouldn't the hearts and endersignal trail item be replaced like the others when you don't have permission for them?

![link](http://i.imgur.com/UVhEXgh.png)
![link1](http://i.imgur.com/dwRzK7d.png)

**Comment by Janmm14** [comment]
Likely to be fixed after my rewrite is pushed: https://github.com/Janmm14/TrailGUI/tree/oop

**Comment by JamieSinn** [comment]
Ah, seems like one commit did not get pushed. Will be fixed today.
